### ISSUE TITLE
race props not loading

### ISSUE THREAD

**Issue by URSFR** [taoletsgo/custom_races#9]
When loading some GTA Online maps there is a specific prop that does not load:

Example:
FiveM:
![20241218233535_1](https://github.com/user-attachments/assets/db300782-3eff-4da2-a416-17c40a66a269)

Gta Online
![20241218234327_1](https://github.com/user-attachments/assets/90ea65cf-fef9-4fb7-ad78-dff44be357f4)

Every time i load the map, the same prop is missing

Here is the json of gta online activity
https://prod.cloud.rockstargames.com/ugc/gta5mission/8117/KULHFMcil06DhZ9v0dgV4Q/0_0_en.json
https://socialclub.rockstargames.com/job/gtav/KULHFMcil06DhZ9v0dgV4Q

Gta V build used on FiveM: 3258

the only thing i modified is the marker, i tried to fix the error but didnt work so i reverted the code

**Comment by taoletsgo** [comment]
I haven't read the source code of FiveM carefully, but I can be sure that many props and objects cannot be used directly. Since the cfx team is not aware of the missing props issue, it is best to stream them.

According to
https://github.com/taoletsgo/custom_races/blob/167512c36fb33c753cb3fc1d644a5b099d6fbc1f/main%20script/custom_races/client/main_client.lua#L2382
https://github.com/taoletsgo/custom_races/blob/167512c36fb33c753cb3fc1d644a5b099d6fbc1f/main%20script/custom_races/client/main_client.lua#L2420

Solution steps:
1. You can find the prop name on https://forge.plebmasters.de/objects according to the error model hash number from F8 console.
2. Search and export the prop file with https://openiv.com/
3. Download https://github.com/indilo53/gtautil/releases, after decompression, right-click in the folder to open the terminal and enter the following command:

```gtautil genpropdefs --input C:\your_path\fixprop\*.ydr --output C:\your_path\fixprop```

![image](https://github.com/user-attachments/assets/24838a6d-ce87-4574-8d06-c9e99ae6bc2c)
5. Create a new resource folder with the following structure:
![image](https://github.com/user-attachments/assets/f1477db1-f750-407c-abd8-c34ad520c511)
6. Edit fxmanifest.lua to:
```lua
fx_version "cerulean"

game "gta5"

data_file "DLC_ITYP_REQUEST" "stream/props.ytyp"
```

7. Restart your server or start the new resource

**Comment by URSFR** [comment]
thanks for answering, i tried searching in the console for not loading props but nothing appears, i added my custom print to make sure the client print works and accesses the function

![20241219030153_1](https://github.com/user-attachments/assets/d6979a98-dfc3-4062-a528-e368eb0f2ed8)

**Comment by taoletsgo** [comment]
emm...werid, the model can be loaded in v2699
![image](https://github.com/user-attachments/assets/d8cd8893-08bf-488e-b2f7-19f1dac8c717)

You can try stream models as described above, replacing local model assets, which may not be created by CreateObjectNoOffset

**Comment by taoletsgo** [comment]
By the way, there is another possible reason. It is best to test in a pure environment, because some anti-cheat scripts will delete stunt props.

**Comment by URSFR** [comment]
sadly the error is happening even with v2699 :/ , the server only has basic-gamemode and the required things for custom-races, i will try to get the props and installing on the server, thanks

**Comment by URSFR** [comment]
after so many tests, i concluded that the object is loading fine no errors, but i detected that the problem is the coordinates of the object, i dont know if you can provide me the json you tested

![20241220053502_1](https://github.com/user-attachments/assets/7f12d66c-4e5b-495f-8ee1-9666054199be)

![strange2](https://github.com/user-attachments/assets/7b1f21ca-ea42-494f-b94e-6d73da21566c)

**Comment by taoletsgo** [comment]
It's the json link you gave me
> https://prod.cloud.rockstargames.com/ugc/gta5mission/8117/KULHFMcil06DhZ9v0dgV4Q/0_0_en.json

And it seems you modified this part
https://github.com/taoletsgo/custom_races/blob/167512c36fb33c753cb3fc1d644a5b099d6fbc1f/main%20script/custom_races/server/races_room.lua#L93-L95
You should make sure the value is float, not integer

Try with og version
https://github.com/taoletsgo/custom_races/releases/tag/v3.0.2

**Comment by taoletsgo** [comment]
And when formatting json, don't turn 0.000 into an integer

**Comment by URSFR** [comment]
i tested 3.0.0 and 3.0.2 og and same problem, i dont know what's happening i test with other object coordinates and works fine, i'm using ctrl + c on rockstar cloud official json

**Comment by taoletsgo** [comment]
> ctrl + c on rockstar

Try `ctrl + s`

_pretty-printing and then ctrl + c is not a good option_

**Comment by URSFR** [comment]
that was the fix, goddamn, life lesson learned, it worked thx

**Comment by taoletsgo** [comment]
https://github.com/taoletsgo/custom_races/blob/167512c36fb33c753cb3fc1d644a5b099d6fbc1f/main%20script/custom_races/server/races_room.lua#L302-L304

It seems that I also need to ensure that the prop value is also a floating point number. Previously, I only ensured the checkpoint part. Thanks for your issue
